import { createFileRoute, Link } from "@tanstack/react-router";
import { Hero } from "@/components/site/Hero";
import { Section, SectionHead } from "@/components/site/Section";
import { PillarGrid } from "@/components/site/PillarCard";
import { CtaBar } from "@/components/site/CtaBar";
import { pageMeta } from "@/lib/seo";
const description="Graviyx's AI is a decision engine, not a chatbot. Four functions embedded in the procurement flow, each with a defined hand-off to a human specialist.";
export const Route=createFileRoute("/intelligence-layer")({head:()=>pageMeta("The Intelligence Layer — AI for Procurement Decisions | GRAVIYX",description),component:IntelligenceLayer});
const functions=[
{title:"01 · Intelligent Client Interaction",stage:"Stage 01, RFQ Intake",trigger:"A buyer enquiry or an incomplete requirement.",action:"Handles the initial enquiry, collects specifications, confirms product availability and generates quotations from live procurement data.",handoff:"Anything it cannot structure or confirm goes to a specialist."},
{title:"02 · Intelligent Procurement Routing",stage:"Stage 02, Review & Shortlist",trigger:"A structured RFQ.",action:"Analyses supplier capabilities and pricing, identifies the most efficient fulfilment route and recommends the fulfilment strategy.",handoff:"The specialist reviews and adjusts the shortlist against human context."},
{title:"03 · Demand Forecasting & Rollout Planning",stage:"Stage 03, Quotations & Compare",trigger:"Confirmed POs and active enquiries accumulate.",action:"Aggregates them into a Rollout Forecast so suppliers can prepare capacity and buyers can hold stable inventory.",handoff:"Specialists turn signals into buying calendars, stocking recommendations and category strategy."},
{title:"04 · Exception Management",stage:"Stage 04, Negotiate & Confirm",trigger:"Activity outside standard parameters.",action:"Surfaces off-spec quotations, price outliers, material shortages, supplier constraints and unresponsive vendors.",handoff:"Escalates automatically to the specialist team. The AI does not attempt to resolve them."}
];
function IntelligenceLayer(){return <>
<Hero eyebrow="The Intelligence Layer" headline="A decision engine, not a chatbot." subhead="Graviyx's AI is an operational intelligence layer embedded in the procurement flow. It moves fast on what is patterned and hands off what needs judgement." />
<Section tone="surface"><SectionHead eyebrow="The principle" title="Bound to stages, not floating." lead="Each function is tied to a specific stage of the RFQ flow. None operates as a general-purpose assistant. When a case falls outside standard parameters, the AI does not decide. It escalates to a specialist." /></Section>
<Section><SectionHead eyebrow="Four functions" title="Trigger → AI action → Human hand-off." /><div className="mt-12 grid gap-4 lg:grid-cols-2">{functions.map(item=><article key={item.title} className="panel p-6 md:p-8"><p className="eyebrow">{item.stage}</p><h3 className="display-sm mt-3 text-fg">{item.title}</h3><dl className="mt-6 space-y-4 text-[15px]"><div><dt className="font-medium text-fg">Trigger</dt><dd className="body-copy mt-1">{item.trigger}</dd></div><div><dt className="font-medium text-fg">AI action</dt><dd className="body-copy mt-1">{item.action}</dd></div><div><dt className="font-medium text-fg">Human hand-off</dt><dd className="body-copy mt-1">{item.handoff}</dd></div></dl></article>)}</div></Section>
<Section tone="warm"><SectionHead eyebrow="What stays with people" title="Negotiation. Escalation. Accountability." lead="First-time and unusual buys stay with people. The AI drafts a PO; a person signs it." /><div className="mt-10"><SectionHead eyebrow="What the AI learns from" title="Every completed deal improves the next." lead="Vendor scorecards, demand signals, warehouse stock positions and the evidence attached to each vendor record improve forecasting and routing accuracy." /><Link to="/fulfillment-warehousing" className="btn btn-secondary mt-7">Fulfilment & Warehousing →</Link></div></Section>
<CtaBar title="See the hand-off on your own requirement." actions={[{label:"Marketplace",to:"/for-buyers"},{label:"Post a Requirement",to:"/post-a-requirement",variant:"secondary"}]} />
</>}
