/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForBuyersRouteImport } from './routes/for-buyers'
import { Route as ForSuppliersRouteImport } from './routes/for-suppliers'
import { Route as FulfillmentWarehousingRouteImport } from './routes/fulfillment-warehousing'
import { Route as HomeVariantA2RouteImport } from './routes/home-variant-a2'
import { Route as HomeVariantERouteImport } from './routes/home-variant-e'
import { Route as HomeVariantJRouteImport } from './routes/home-variant-j'
import { Route as HomeVariantKRouteImport } from './routes/home-variant-k'
import { Route as HomeVariantLRouteImport } from './routes/home-variant-l'
import { Route as HomeVariantMRouteImport } from './routes/home-variant-m'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IntelligenceLayerRouteImport } from './routes/intelligence-layer'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerWithUsRouteImport } from './routes/partner-with-us'
import { Route as PostARequirementRouteImport } from './routes/post-a-requirement'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal.terms-of-service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuyersRoute = ForBuyersRouteImport.update({
  id: '/for-buyers',
  path: '/for-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForSuppliersRoute = ForSuppliersRouteImport.update({
  id: '/for-suppliers',
  path: '/for-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentWarehousingRoute = FulfillmentWarehousingRouteImport.update({
  id: '/fulfillment-warehousing',
  path: '/fulfillment-warehousing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantA2Route = HomeVariantA2RouteImport.update({
  id: '/home-variant-a2',
  path: '/home-variant-a2',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantERoute = HomeVariantERouteImport.update({
  id: '/home-variant-e',
  path: '/home-variant-e',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantJRoute = HomeVariantJRouteImport.update({
  id: '/home-variant-j',
  path: '/home-variant-j',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantKRoute = HomeVariantKRouteImport.update({
  id: '/home-variant-k',
  path: '/home-variant-k',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantLRoute = HomeVariantLRouteImport.update({
  id: '/home-variant-l',
  path: '/home-variant-l',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVariantMRoute = HomeVariantMRouteImport.update({
  id: '/home-variant-m',
  path: '/home-variant-m',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceLayerRoute = IntelligenceLayerRouteImport.update({
  id: '/intelligence-layer',
  path: '/intelligence-layer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerWithUsRoute = PartnerWithUsRouteImport.update({
  id: '/partner-with-us',
  path: '/partner-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PostARequirementRoute = PostARequirementRouteImport.update({
  id: '/post-a-requirement',
  path: '/post-a-requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/fulfillment-warehousing': typeof FulfillmentWarehousingRoute
  '/home-variant-a2': typeof HomeVariantA2Route
  '/home-variant-e': typeof HomeVariantERoute
  '/home-variant-j': typeof HomeVariantJRoute
  '/home-variant-k': typeof HomeVariantKRoute
  '/home-variant-l': typeof HomeVariantLRoute
  '/home-variant-m': typeof HomeVariantMRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/intelligence-layer': typeof IntelligenceLayerRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/post-a-requirement': typeof PostARequirementRoute
  '/trust': typeof TrustRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/fulfillment-warehousing': typeof FulfillmentWarehousingRoute
  '/home-variant-a2': typeof HomeVariantA2Route
  '/home-variant-e': typeof HomeVariantERoute
  '/home-variant-j': typeof HomeVariantJRoute
  '/home-variant-k': typeof HomeVariantKRoute
  '/home-variant-l': typeof HomeVariantLRoute
  '/home-variant-m': typeof HomeVariantMRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/intelligence-layer': typeof IntelligenceLayerRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/post-a-requirement': typeof PostARequirementRoute
  '/trust': typeof TrustRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/for-buyers': typeof ForBuyersRoute
  '/for-suppliers': typeof ForSuppliersRoute
  '/fulfillment-warehousing': typeof FulfillmentWarehousingRoute
  '/home-variant-a2': typeof HomeVariantA2Route
  '/home-variant-e': typeof HomeVariantERoute
  '/home-variant-j': typeof HomeVariantJRoute
  '/home-variant-k': typeof HomeVariantKRoute
  '/home-variant-l': typeof HomeVariantLRoute
  '/home-variant-m': typeof HomeVariantMRoute
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRoute
  '/intelligence-layer': typeof IntelligenceLayerRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/partner-with-us': typeof PartnerWithUsRoute
  '/post-a-requirement': typeof PostARequirementRoute
  '/trust': typeof TrustRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/for-buyers'
    | '/for-suppliers'
    | '/fulfillment-warehousing'
    | '/home-variant-a2'
    | '/home-variant-e'
    | '/home-variant-j'
    | '/home-variant-k'
    | '/home-variant-l'
    | '/home-variant-m'
    | '/how-it-works'
    | '/industries'
    | '/insights'
    | '/intelligence-layer'
    | '/legal'
    | '/login'
    | '/partner-with-us'
    | '/post-a-requirement'
    | '/trust'
    | '/legal/privacy-policy'
    | '/legal/security'
    | '/legal/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/for-buyers'
    | '/for-suppliers'
    | '/fulfillment-warehousing'
    | '/home-variant-a2'
    | '/home-variant-e'
    | '/home-variant-j'
    | '/home-variant-k'
    | '/home-variant-l'
    | '/home-variant-m'
    | '/how-it-works'
    | '/industries'
    | '/insights'
    | '/intelligence-layer'
    | '/legal'
    | '/login'
    | '/partner-with-us'
    | '/post-a-requirement'
    | '/trust'
    | '/legal/privacy-policy'
    | '/legal/security'
    | '/legal/terms-of-service'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/for-buyers'
    | '/for-suppliers'
    | '/fulfillment-warehousing'
    | '/home-variant-a2'
    | '/home-variant-e'
    | '/home-variant-j'
    | '/home-variant-k'
    | '/home-variant-l'
    | '/home-variant-m'
    | '/how-it-works'
    | '/industries'
    | '/insights'
    | '/intelligence-layer'
    | '/legal'
    | '/login'
    | '/partner-with-us'
    | '/post-a-requirement'
    | '/trust'
    | '/legal/privacy-policy'
    | '/legal/security'
    | '/legal/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ForBuyersRoute: typeof ForBuyersRoute
  ForSuppliersRoute: typeof ForSuppliersRoute
  FulfillmentWarehousingRoute: typeof FulfillmentWarehousingRoute
  HomeVariantA2Route: typeof HomeVariantA2Route
  HomeVariantERoute: typeof HomeVariantERoute
  HomeVariantJRoute: typeof HomeVariantJRoute
  HomeVariantKRoute: typeof HomeVariantKRoute
  HomeVariantLRoute: typeof HomeVariantLRoute
  HomeVariantMRoute: typeof HomeVariantMRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRoute
  IntelligenceLayerRoute: typeof IntelligenceLayerRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnerWithUsRoute: typeof PartnerWithUsRoute
  PostARequirementRoute: typeof PostARequirementRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-buyers': {
      id: '/for-buyers'
      path: '/for-buyers'
      fullPath: '/for-buyers'
      preLoaderRoute: typeof ForBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-suppliers': {
      id: '/for-suppliers'
      path: '/for-suppliers'
      fullPath: '/for-suppliers'
      preLoaderRoute: typeof ForSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment-warehousing': {
      id: '/fulfillment-warehousing'
      path: '/fulfillment-warehousing'
      fullPath: '/fulfillment-warehousing'
      preLoaderRoute: typeof FulfillmentWarehousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-a2': {
      id: '/home-variant-a2'
      path: '/home-variant-a2'
      fullPath: '/home-variant-a2'
      preLoaderRoute: typeof HomeVariantA2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-e': {
      id: '/home-variant-e'
      path: '/home-variant-e'
      fullPath: '/home-variant-e'
      preLoaderRoute: typeof HomeVariantERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-j': {
      id: '/home-variant-j'
      path: '/home-variant-j'
      fullPath: '/home-variant-j'
      preLoaderRoute: typeof HomeVariantJRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-k': {
      id: '/home-variant-k'
      path: '/home-variant-k'
      fullPath: '/home-variant-k'
      preLoaderRoute: typeof HomeVariantKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-l': {
      id: '/home-variant-l'
      path: '/home-variant-l'
      fullPath: '/home-variant-l'
      preLoaderRoute: typeof HomeVariantLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-variant-m': {
      id: '/home-variant-m'
      path: '/home-variant-m'
      fullPath: '/home-variant-m'
      preLoaderRoute: typeof HomeVariantMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence-layer': {
      id: '/intelligence-layer'
      path: '/intelligence-layer'
      fullPath: '/intelligence-layer'
      preLoaderRoute: typeof IntelligenceLayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-with-us': {
      id: '/partner-with-us'
      path: '/partner-with-us'
      fullPath: '/partner-with-us'
      preLoaderRoute: typeof PartnerWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-a-requirement': {
      id: '/post-a-requirement'
      path: '/post-a-requirement'
      fullPath: '/post-a-requirement'
      preLoaderRoute: typeof PostARequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ForBuyersRoute: ForBuyersRoute,
  ForSuppliersRoute: ForSuppliersRoute,
  FulfillmentWarehousingRoute: FulfillmentWarehousingRoute,
  HomeVariantA2Route: HomeVariantA2Route,
  HomeVariantERoute: HomeVariantERoute,
  HomeVariantJRoute: HomeVariantJRoute,
  HomeVariantKRoute: HomeVariantKRoute,
  HomeVariantLRoute: HomeVariantLRoute,
  HomeVariantMRoute: HomeVariantMRoute,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRoute,
  IntelligenceLayerRoute: IntelligenceLayerRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnerWithUsRoute: PartnerWithUsRoute,
  PostARequirementRoute: PostARequirementRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
